version: '2'
volumes:
  pictures:
services:
  frontend:
    build: ./frontend
    expose:
      - "3000"
    privileged: true
    volumes:
      - "pictures:/pictures" 
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
    ports:
      - "80:80"
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  wpe:
    restart: always
    build: ./wpe
    privileged: true
    ports:
      - 8080:8080
 