version: '2'
volumes:
  - pictures:
services:
  frontend:
    build: ./frontend
    expose:
      - "3000"
    privileged: true
    volumes:
      - "pictures:/pictures" 
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
    ports:
      - "80:80"
  wpe:
    build: ./wpe
    depends_on:
      - proxy
      - frontend
    privileged: true
