version: '2'
services:
  frontend:
    build: ./frontend
    expose:
      - "3000"
    privileged: true
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
    ports:
      - "80:80"
  wpe:
    build: ./wpe
    depends_on:
      - proxy
      - frontend
    privileged: true
