#!/bin/sh

udevd &
udevadm trigger

fbcp &

# Set the backlight brightness of a Raspberry touchscreen
# The environment variable RPI_BACKLIGHT can be set to a value 0-255.
export RPI_BACKLIGHT=${RPI_BACKLIGHT:-255}
if [ -f /sys/class/backlight/rpi_backlight/brightness ]; then
	echo $RPI_BACKLIGHT > /sys/class/backlight/rpi_backlight/brightness
fi

# Writable directories. See documentation here:
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export HOME=/tmp/balena
mkdir -p /tmp/balena/xdg_runtime
chmod 0700 /tmp/balena/xdg_runtime
export XDG_RUNTIME_DIR=/tmp/balena/xdg_runtime

# Enable touch screen
export WPE_BCMRPI_TOUCH=1

# Start Tohora
./tohora 8080 cog &

# wait for it
sleep 15

# Check if we have a  WPE_URL var
if [[ -z ${WPE_URL} ]]
  then
    echo "Loading default page"
    # sleep 1
    wget --post-data "url=file:///var/lib/public_html/index.html" http://localhost:8080/launch/
  else
    echo "Loading booth page"
    # sleep 10
    wget --post-data "url=${WPE_URL}" http://localhost:8080/launch/
fi

tail -f /dev/null